---
title: "Untitled"
author: "cai wang"
date: "14/10/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(phyloseq)
library(decontam)
```


```{r separate sequnce}
OTUseq<-read.csv("spongetank_all_SWARM_FINAL_OTU_20211011.csv", header=TRUE)
seq<-apply(OTUseq, 1, function(x){paste0(">",x[1],"\n",x[121])})
writeLines(seq)
write.table(seq,file="spongetank_all_SWARM_FINAL_OTU.fasta",row.names = F,quote=F)
#delete x
OTUtab<-OTUseq %>% select (D1.SW.BLANK:LIB02.PCR.Pos.03)
rownames(OTUtab)=OTUseq$id
```

```{r code for LuLu (use to fiter ech OTU), eval=FALSE }
#1.#filter echo OTU
##terminal##vsearch --usearch_global spongetank_all_SWARM_FINAL_OTU.fasta --db spongetank_all_SWARM_FINAL_OTU.fasta --self --id .84 --iddef 1 --userout match_list.txt -userfields query+target+id --maxaccepts 0 --query_cov .9 --maxhits 10 
#install.packages("devtools")
#library(devtools)
#install_github("tobiasgf/lulu") 
library(lulu)
matchlist <- read.table("match_list.txt", header=FALSE,as.is=TRUE, stringsAsFactors=FALSE)

curated_result <- lulu(OTUtab, matchlist, minimum_ratio_type = "min", minimum_ratio = 1, minimum_match = 84, minimum_relative_cooccurence = 0.95)
#compare the result
#curated_result$curated_table
#curated_result$original_table
curated_result$discarded_coun
OTUtax <-OTUseq[OTUseq$id %in% rownames(curated_result$curated_table),]
write.csv(OTUtax, file = "spongetank_SWARM_OTU_LULU_FULL_20211014.csv",row.names = TRUE, quote = FALSE)
#write.csv(curated_result$curated_table, file = "spongetank_SWARM_OTU_LULU_20211014.csv",row.names = TRUE, quote = FALSE)
rm(list=ls())
```

```{r collapse OTUs on terminal}
#collapse MOTUs on terminal
#Rscript /Users/wang/Desktop/ob1_mbc/R_scripts_metabarpark/owi_collapse -s 16 -e 116 -t 0.50 -i spongetank_SWARM_OTU_LULU_FULL_20211014.csv
#-s 14 Sample columns start; -e sample columns end. Default = 98; -t 0.50 Threshold for collapsing
```

```{r phyloseq formal}
OTUseq<-read.csv("spongetank_SWARM_OTU_LULU_FULL_20211014_collapsed.csv", header=TRUE)
#otu_table
OTU<-OTUseq %>% select (D1.SW.BLANK:LIB02.PCR.Pos.03)
rownames(OTU)=OTUseq$id

#tax_table
TAX<-OTUseq %>% select (kingdom_name:species_name)
rownames(TAX)=OTUseq$id
TAX <- as.matrix(TAX)

#sample_data
sample_data<-read.csv("sampledata20211014.csv", header=TRUE)
sample_data$quant_reading=colSums(OTU)
rownames(sample_data)=sample_data$name

#####filter total reads=0 samples
sample_data=sample_data %>% filter(quant_reading!=0)
OTU= OTU %>% select(sample_data$name)
OTU <- as.matrix(OTU)
###write the phyloseq format
physeq_spongetank = phyloseq(otu_table(OTU, taxa_are_rows = TRUE), tax_table(TAX), sample_data(sample_data))
```

```{r}
contamdf.freq <- isContaminant(physeq_spongetank, method="frequency", conc="quant_reading",batch = "RUN")
table(contamdf.freq$contaminant)
decontam.T=contamdf.freq %>% filter(contaminant=="TRUE")
#plot all the decontam otus
T.n=which(rownames(OTU)%in% rownames(decondem.T)==TRUE)
plot_frequency(physeq_spongetank, taxa_names(physeq_spongetank)[c(T.n)], conc="quant_reading") + 
  xlab("DNA Concentration (PicoGreen fluorescent intensity)")
TAX[T.n,7]
#delect decontam=Ture seq.
ps.noncontam <- prune_taxa(!contamdf.freq$contaminant, physeq_spongetank)

save(ps.noncontam,physeq_spongetank,file = "physeq_spongetank_noncontam.rdata")
```

```{r}
OTU<- data.frame(t(as.data.frame(otu_table(ps.noncontam))))
metadata<- data.frame(sample_data(ps.noncontam)) 
#OTU.tank<- OTU %>% filter (metadata$experiment=="tank")
#OTU.tank.water<- OTU %>% filter (metadata$sponge_type=="WATER" & metadata$experiment=="tank")

metadata.hour<- metadata %>% filter (metadata$hour != "CONTROL" & metadata$hour != "BLANK" & metadata$hour != "NO" & metadata$hour != "Pos"  & metadata$hour != "Neg")
metadata.hour <- metadata.hour %>%
  mutate(
    hour = case_when(
      hour == "env" ~ "0",
      hour == "0" ~ "48",
      hour == "1" ~ "24",
      hour == "4" ~ "52",
      hour == "8" ~ "56",
      hour == "24" ~ "72",
      hour == "48" ~ "96",
      hour == "72" ~ "120",
      TRUE ~ as.character(hour)
    )
  )

metadata.hour$hour=as.numeric(metadata.hour$hour)

#total reads
ggplot(data=metadata.hour, aes(x=hour, y=quant_reading, colour= tank))+ geom_line(size=0.3)+geom_point()+facet_wrap(~sponge_type, nrow =8)

#species
OTU.tank=OTU %>% filter (metadata$hour != "CONTROL" & metadata$hour != "BLANK" & metadata$hour != "NO" & metadata$hour != "Pos"  & metadata$hour != "Neg")
otu.Amphiprion=OTU.tank%>% select(tank_000000028)
otu.Chromis=OTU.tank %>% select(tank_000000158)
otu.a=OTU.tank %>% select(tank_000000013)
otu.b=OTU.tank %>% select(tank_000000035)
otu.c=OTU.tank %>% select(tank_000000021)

metadata.hour.1=bind_cols(metadata.hour,otu.Amphiprion) %>% mutate(species="Amphiprion")%>% rename(read = tank_000000028)
metadata.hour.2=bind_cols(metadata.hour,otu.Chromis) %>% mutate(species="Chromis")%>% rename(read = tank_000000158)
metadata.hour.3=bind_cols(metadata.hour,otu.a) %>% mutate(species="Zebrasoma")%>% rename(read = tank_000000013)
metadata.hour.4=bind_cols(metadata.hour,otu.b) %>% mutate(species="Gramma")%>% rename(read = tank_000000035)
metadata.hour.5=bind_cols(metadata.hour,otu.c) %>% mutate(species="Hippocampus")%>% rename(read = tank_000000021)

metadata.hour=bind_rows(metadata.hour.1,metadata.hour.2,metadata.hour.3,metadata.hour.4,metadata.hour.5)

ggplot(data=metadata.hour, aes(x=hour, y=read, colour= species))+ geom_line(size=0.3)+geom_point()+facet_grid(sponge_type ~ tank)
ggplot(data=metadata.hour, aes(x=hour, y=read, colour= sponge_type))+ geom_line(size=0.3)+geom_point()+facet_grid(species ~ tank)

metadata.hour.water=metadata.hour %>% filter(sponge_type=="WATER")
metadata.hour.CREAM=metadata.hour %>% filter(sponge_type=="CREAM")
metadata.hour.pine=metadata.hour %>% filter(sponge_type=="PINK")

ggplot(data=metadata.hour.pine, aes(x=hour, y=read, colour= species))+ geom_line(size=0.3)+geom_point()+facet_grid(species ~ tank)
```

